### ISSUE TITLE
Should variation selectors be mapped to a glyph too?

### ISSUE THREAD

**Issue by Lucide** [adobe-fonts/adobe-notdef#1]
HI, I've noticed that Unicodes' [Variation Selectors](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) are mapped too. Is this by design?
I've read that *some* non-characters are excluded. Variation selectors perhaps should be too, they do actual work, but can't be used here.

**Comment by punchcutter** [comment]
A very late reply, but yes the mapping of Variation Selectors is by design. However, they might not work in every application. In InDesign you can see them as separate glyphs and even copy/paste the VS itself which you wouldn't be able to do otherwise.
