### ISSUE TITLE
Devanagari support

### ISSUE THREAD

**Issue by rramphal** [adobe-fonts/adobe-notdef#3]
Does Adobe NotDef support the Devanagari script?

Here's a simple example to reproduce:

```html
<html>
    <head>
        <meta charset="UTF-8" />

        <style>
            div {
                font-family: "Symbol", "Adobe NotDef";
            }
        </style>
    </head>

    <body>
        <h2>Devanagari</h2>
        <div>देवनागरी</div>

        <h2>Chinese</h2>
        <div>中文</div>
    </body>
</html>
```

and here is how it renders on my system:

<img src="https://user-images.githubusercontent.com/6126950/163675683-153337b3-5e4e-416b-a5d7-adef0f3a32cf.png" width="500px" />

I also noticed that emojis seem to be consistently rendered, but I have a feeling that has more to do with how MacOS handles the Apple Color Emoji font. Other charsets I have tested seem to be handled correctly by Adobe NotDef.

**Comment by punchcutter** [comment]
You should see .notdef glyphs for Devanagari. It looks like with the example you have it's just using fallback, but the font itself will return multiple .notdefs for that string so the problem seems to be elsewhere.

**Comment by rramphal** [comment]
Hmm, that's what I thought.

I just tested on Chrome, Firefox, and Safari. Chrome correctly renders `.notdef` glyphs for both Devanagari and Chinese. Firefox shows the above behavior where the Chinese correctly shows the `.notdef` glyphs, but incorrectly renders the Devanagari. Safari surprisingly does not show `.notdef` glyphs for neither Devanagari nor Chinese.

Obviously, the issue is not with the font, and instead with how these different browsers handle the font, so I'll close this issue. Thank you for your help!
